name: e_commerce_restaurant
description: A new Flutter project for E-Commerce Restaurant App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  auto_route: ^5.0.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

 uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg